import { GoogleGenAI, Type, Schema } from "@google/genai";
import { MemeContent } from '../types';

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const MEME_SYSTEM_INSTRUCTION = `
You are an expert Web Development Meme Creator AI. 
Your task is to take a user's coding topic or struggle and convert it into a funny, relatable meme concept.

You must output a JSON object with three fields:
1. "topText": Short, punchy text for the top of the meme.
2. "bottomText": Short, punchy punchline for the bottom of the meme.
3. "imagePrompt": A highly descriptive visual prompt for an image generation model to create the background.

Guidelines:
- Humor Topics: HTML/CSS, JS, React, Backend, Debugging, Git, Senior vs Junior, Deadlines.
- Style: Classic meme format (Top/Bottom text).
- The "imagePrompt" must describe a cartoon or illustration style scene. 
- IMPORTANT: The "imagePrompt" must NOT include any text instructions for the image itself. The image should be text-free so we can overlay the meme text later.
- Make the visual description exaggerated and funny (e.g., "a skeleton sitting at a computer covered in cobwebs", "a raccoon trying to fix a server rack on fire").
`;

export const generateMemeContent = async (topic: string, templateContext?: string): Promise<MemeContent> => {
  let instruction = MEME_SYSTEM_INSTRUCTION;
  
  if (templateContext) {
    instruction += `\n\nCONTEXT: The user has selected a specific background image described as: "${templateContext}". 
    Your generated "topText" and "bottomText" MUST fit this visual context perfectly while relating to the topic "${topic}".
    Ignore the requirement to generate a new "imagePrompt" based on the topic; instead, focus strictly on making the text match the provided image description.`;
  }

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: `Topic: ${topic}`,
    config: {
      systemInstruction: instruction,
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          topText: { type: Type.STRING },
          bottomText: { type: Type.STRING },
          imagePrompt: { type: Type.STRING },
        },
        required: ["topText", "bottomText", "imagePrompt"]
      } as Schema
    }
  });

  const text = response.text;
  if (!text) throw new Error("No response from Gemini");
  return JSON.parse(text) as MemeContent;
};

export const generateMemeImage = async (imagePrompt: string): Promise<string> => {
  const fullPrompt = `A high-quality, funny digital art cartoon illustration of: ${imagePrompt}. 
  Vibrant colors, expressive characters, web developer humor style. 
  NO TEXT, NO WORDS, NO LETTERS inside the artwork.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image', // Using flash-image for speed and good cartoon adherence
    contents: {
      parts: [
        { text: fullPrompt }
      ]
    },
    // No specific config needed for basic generation, the model defaults are good.
  });

  // Iterate to find the image part
  for (const candidate of response.candidates || []) {
    for (const part of candidate.content.parts) {
      if (part.inlineData && part.inlineData.mimeType.startsWith('image/')) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
  }

  throw new Error("No image generated by Gemini");
};
